AWSTemplateFormatVersion: '2010-09-09'
Description: A simple template to create an S3 bucket.

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'my-s3-bucket-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  BucketName:
    Description: 'Name of the S3 bucket'
    Value: !Ref MyS3Bucket
  BucketURL:
    Description: 'URL of the S3 bucket'
    Value: !Sub 'https://${MyS3Bucket}.s3.amazonaws.com'
