AWSTemplateFormatVersion: '2010-09-09'
Description: >
  AWS CloudFormation Template for deploying a basic single-instance WordPress site
  with EC2, RDS (MySQL), and security group configuration.

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Description: EC2 instance type for the WordPress host
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
      - t3.small
    ConstraintDescription: must be a valid EC2 instance type.

  DBName:
    Default: wordpressdb
    Description: The name of the MySQL database
    Type: String

  DBUser:
    Default: admin
    NoEcho: true
    Description: The MySQL database admin account username
    Type: String

  DBPassword:
    Default: password12345
    NoEcho: true
    Description: The MySQL database admin account password
    Type: String

  DBAllocatedStorage:
    Default: 20
    Description: The size of the database (Gb)
    Type: Number
    MinValue: 5
    MaxValue: 1024

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MySQLSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL from web server
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref WebServerSecurityGroup

  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !Ref DBAllocatedStorage
      DBInstanceClass: db.t3.micro
      Engine: MySQL
      MasterUsername: !Ref DBUser
      MasterUserPassword: !Ref DBPassword
      DBName: !Ref DBName
      VPCSecurityGroups: [ !Ref MySQLSecurityGroup ]
      PubliclyAccessible: true

  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 AMI (adjust for your region)
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install -y php7.4
          yum install -y httpd php php-mysqlnd mariadb
          systemctl enable httpd
          systemctl start httpd
          cd /var/www/html
          wget https://wordpress.org/latest.tar.gz
          tar -xzf latest.tar.gz
          cp -r wordpress/* .
          rm -rf wordpress latest.tar.gz
          cp wp-config-sample.php wp-config.php
          sed -i "s/database_name_here/${DBName}/" wp-config.php
          sed -i "s/username_here/${DBUser}/" wp-config.php
          sed -i "s/password_here/${DBPassword}/" wp-config.php
          echo "define('FS_METHOD', 'direct');" >> wp-config.php

Outputs:
  WebsiteURL:
    Description: URL of the WordPress site
    Value: !Sub "http://${WebServerInstance.PublicDnsName}"
